/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/request-otp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Запрос одноразового кода подтверждения
     * @description Создаёт и отправляет OTP пользователю.
     */
    post: operations['requestOtp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify-otp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Подтверждение одноразового кода
     * @description Проверяет OTP и возвращает пару токенов.
     */
    post: operations['verifyOtp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Обновление токенов авторизации
     * @description Обновляет токены по refresh-cookie или заголовку.
     */
    get: operations['refresh'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/complete-profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Дополнение профиля пользователя
     * @description Обновляет профиль после первичного входа.
     */
    post: operations['completeProfile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Выход из аккаунта
     * @description Удаляет текущую сессию пользователя.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение текущего пользователя
     * @description Возвращает профиль текущего пользователя.
     */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Обновление профиля пользователя
     * @description Обновляет профиль текущего пользователя.
     */
    patch: operations['updateProfile'];
    trace?: never;
  };
  '/me/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение списка активных сессий
     * @description Возвращает список активных сессий текущего пользователя.
     */
    get: operations['getMeSessions'];
    put?: never;
    post?: never;
    /**
     * Выход со всех устройств
     * @description Удаляет все сессии текущего пользователя, кроме текущей.
     */
    delete: operations['deleteAllSessions'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/sessions/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Удаление сессии
     * @description Удаляет указанную сессию текущего пользователя.
     */
    delete: operations['deleteSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение списка всех ролей
     * @description Возвращает список всех ролей в системе.
     */
    get: operations['getRoles'];
    put?: never;
    /**
     * Создание роли
     * @description Создаёт новую роль с указанными разрешениями.
     */
    post: operations['createRole'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/roles/permissions-schema': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение схемы разрешений
     * @description Возвращает схему всех доступных разрешений для построения UI.
     */
    get: operations['getPermissionsSchema'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/roles/{roleId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение роли по ID
     * @description Возвращает детальную информацию о роли.
     */
    get: operations['getRole'];
    put?: never;
    post?: never;
    /**
     * Удаление роли
     * @description Удаляет роль и переназначает всех пользователей на замещающую роль. Статические роли не могут быть удалены.
     */
    delete: operations['deleteRole'];
    options?: never;
    head?: never;
    /**
     * Обновление разрешений роли
     * @description Обновляет разрешения указанной роли. Статические роли не могут быть изменены.
     */
    patch: operations['updateRole'];
    trace?: never;
  };
  '/users/{userId}/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Назначение роли пользователю
     * @description Обновляет роль пользователя. Все сессии пользователя будут удалены.
     */
    patch: operations['updateUserRole'];
    trace?: never;
  };
  '/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Поиск пользователей (admin)
     * @description Поиск пользователей с фильтрацией по роли и текстовому запросу.
     */
    get: operations['searchAdminUsers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/upload-request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Получение presigned URL для загрузки файла
     * @description Возвращает presigned URL и идентификатор файла для загрузки.
     */
    post: operations['mediaUploadRequest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/confirm-upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Подтверждение загрузки файлов
     * @description Переводит загруженные файлы из временного хранилища в постоянное.
     */
    post: operations['mediaConfirmUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/preview/{mediaId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение preview URL для временного файла
     * @description Возвращает presigned URL для предпросмотра файла до подтверждения загрузки.
     */
    get: operations['mediaPreview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/banners': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get all banners */
    get: operations['getBanners'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorDetail: {
      /** @description Код ошибки для обработки на клиенте */
      errorCode: string;
      /** @description Человекочитаемое описание ошибки */
      message: string;
      /** @description Путь к полю с ошибкой */
      path: string;
      /** @description Дополнительные детали ошибки */
      data?: {
        [key: string]: unknown;
      };
    };
    OpenApiValidationError: {
      /** @description HTTP код ответа */
      statusCode: number;
      /** @enum {boolean} */
      isDomain: false;
      /** @description Человекочитаемое описание ошибки */
      message: string;
      errors: components['schemas']['ErrorDetail'][];
    };
    DomainErrorResponse: {
      /** @description Код ошибки для обработки на клиенте */
      type: string;
      /** @description Человекочитаемое описание ошибки */
      message?: string;
      /** @enum {boolean} */
      isDomain: true;
      /** @description Дополнительные детали ошибки */
      data?: {
        [key: string]: unknown;
      };
    };
    ThrottledErrorResponse: {
      /** @enum {string} */
      type: 'throttled';
      message?: string;
      data: {
        /** @description Рекомендованная задержка перед повторной попыткой */
        retryAfterSec: number;
      };
    };
    TokenPair: {
      /** @description JWT access-токен */
      accessToken: string;
      /** @description JWT refresh-токен */
      refreshToken: string;
    };
    /** @enum {string} */
    MediaVisibility: 'PUBLIC' | 'PRIVATE';
    LinkMediaData: {
      bucket: string;
      objectKey: string;
      /** @description Идентификатор загруженного медиа-объекта */
      mediaId: string;
      visibility: components['schemas']['MediaVisibility'];
      contentType?: string;
    };
    Avatar: {
      /** Format: uri */
      largeUrl: string;
      /** Format: uri */
      mediumUrl: string;
      /** Format: uri */
      smallUrl: string;
      /** Format: uri */
      thumbUrl: string;
    };
    User: {
      /**
       * Format: uuid
       * @description Уникальный идентификатор пользователя
       */
      id: string;
      /** @description Телефон в формате E.164 */
      phoneNumber: string;
      fullName?: string;
      avatar?: components['schemas']['Avatar'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserSession: {
      /**
       * Format: uuid
       * @description Идентификатор сессии
       */
      id: string;
      /**
       * Format: date-time
       * @description Дата создания сессии
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Дата истечения сессии
       */
      expiresAt: string;
    };
    Role: {
      /** Format: uuid */
      id: string;
      name: string;
      permissions: {
        [key: string]: unknown;
      };
      isStatic: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UploadRequest: {
      name: string;
      mimeType: string;
      bucket: string;
    };
    UploadRequestResult: {
      fileId: string;
      /** Format: uri */
      uploadUrl: string;
    };
    ConfirmUploadInput: {
      fileIds: string[];
    };
    PreviewDownloadUrlResult: {
      /** Format: uri */
      url: string;
    };
    DateRange: {
      /** Format: date-time */
      from?: string;
      /** Format: date-time */
      to?: string;
    };
    Pagination: {
      after?: string;
      before?: string;
      first?: number;
      last?: number;
    };
    /** @enum {string} */
    SortDirection: 'ASC' | 'DESC';
    Sort: {
      direction?: components['schemas']['SortDirection'];
      field?: string;
    };
    BannerFile: {
      /** Format: uuid */
      id: string;
      /** Format: uri */
      url: string;
    };
    Banner: {
      /** Format: date-time */
      createdAt: string;
      /** Format: uuid */
      id: string;
      isNew: boolean;
      logo: components['schemas']['BannerFile'];
      opacity: number;
      sequence: number;
      subtitle?: string | null;
      title?: string | null;
      url?: string | null;
    };
    BannerEdge: {
      cursor?: string | null;
      node: components['schemas']['Banner'];
    };
    PageInfo: {
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  requestOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Телефон в формате E.164 */
          phoneNumber: string;
          /**
           * @description Канал доставки OTP
           * @enum {string}
           */
          channel?: 'sms' | 'whatsapp';
          /** @description Локаль для текстов уведомлений */
          locale?: string;
        };
      };
    };
    responses: {
      /** @description OTP отправлен */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Рекомендованная задержка до следующего запроса OTP */
            nextRetrySec?: number;
          };
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Превышено количество попыток */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            type: 'login_blocked';
            message?: string;
            /** @enum {boolean} */
            isDomain: true;
            /** @description Рекомендованная задержка перед повторной попыткой */
            retryAfterSec?: number;
          };
        };
      };
      /** @description Слишком много запросов */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ThrottledErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  verifyOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Телефон в формате E.164 */
          phoneNumber: string;
          /** @description Код подтверждения из SMS */
          code: string;
        };
      };
    };
    responses: {
      /** @description Авторизация успешна */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                /** @enum {string} */
                type: 'authenticated';
                /** @description JWT access-токен */
                accessToken: string;
                /** @description JWT refresh-токен */
                refreshToken: string;
              }
            | {
                /** @enum {string} */
                type: 'new_registration';
                /** @description Идентификатор сессии регистрации */
                registrationSessionId: string;
              };
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Превышено количество попыток */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            type: 'login_blocked';
            message?: string;
            /** @enum {boolean} */
            isDomain: true;
            retryAfterSec?: number;
          };
        };
      };
      /** @description Слишком много запросов */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ThrottledErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header: {
        'x-refresh-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Токены обновлены */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPair'];
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Невалидный refresh-токен */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  completeProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Идентификатор сессии регистрации из verifyOtp */
          registrationSessionId: string;
          fullName?: string;
          avatarMedia?: components['schemas']['LinkMediaData'];
        };
      };
    };
    responses: {
      /** @description Профиль создан, токены выданы */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: components['schemas']['User'];
            /** @description JWT access-токен */
            accessToken: string;
            /** @description JWT refresh-токен */
            refreshToken: string;
          };
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Сессия удалена */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Профиль пользователя */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Полное имя пользователя */
          fullName: string;
        };
      };
    };
    responses: {
      /** @description Обновлённый профиль */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  getMeSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Список сессий */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            sessions: components['schemas']['UserSession'][];
          };
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  deleteAllSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Все сессии удалены */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  deleteSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Сессия удалена */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Ошибка валидации */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Сессия не найдена */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  getRoles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Список ролей */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            roles: components['schemas']['Role'][];
          };
        };
      };
      /** @description Нет доступа */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  createRole: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
          permissions?: {
            [key: string]: unknown;
          };
        };
      };
    };
    responses: {
      /** @description Роль создана */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
      /** @description Ошибка валидации или роль уже существует */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | {
                /** @enum {string} */
                type: 'role_already_exists';
                message?: string;
                /** @enum {boolean} */
                isDomain: true;
              };
        };
      };
      /** @description Нет доступа */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Роль не найдена */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  getPermissionsSchema: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Схема разрешений */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            action: string;
            key: string;
            /** @enum {string} */
            type: 'boolean' | 'enum';
            values?: string[];
            default: unknown;
          }[];
        };
      };
      /** @description Нет доступа */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  getRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Роль */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
      /** @description Ошибка валидации */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
      /** @description Нет доступа */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Роль не найдена */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  deleteRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roleId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uuid */
          replacementRoleId: string;
        };
      };
    };
    responses: {
      /** @description Роль удалена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Нельзя удалить статическую роль */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Роль не найдена */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  updateRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roleId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          permissions: {
            [key: string]: unknown;
          };
        };
      };
    };
    responses: {
      /** @description Роль обновлена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Нельзя изменить статическую роль */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Роль не найдена */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  updateUserRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uuid */
          roleId: string;
        };
      };
    };
    responses: {
      /** @description Роль пользователя обновлена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Нет доступа */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Пользователь или роль не найдены */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  searchAdminUsers: {
    parameters: {
      query?: {
        /** @description Текстовый поисковый запрос */
        query?: string;
        /** @description Фильтр по роли */
        role?: string;
        /** @description Смещение для пагинации */
        from?: number;
        /** @description Размер страницы */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Результаты поиска */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            users: {
              /** Format: uuid */
              userId: string;
              phoneNumber: string;
              fullName: string;
              role: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            }[];
            total: number;
          };
        };
      };
      /** @description Ошибка валидации */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
      /** @description Нет доступа */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  mediaUploadRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UploadRequest'];
      };
    };
    responses: {
      /** @description Presigned URL для загрузки */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadRequestResult'];
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Файл не найден */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  mediaConfirmUpload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmUploadInput'];
      };
    };
    responses: {
      /** @description Загрузка подтверждена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
      /** @description Ошибка валидации / Доменная ошибка */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['OpenApiValidationError']
            | components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Файл не найден */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  mediaPreview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mediaId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Preview URL */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreviewDownloadUrlResult'];
        };
      };
      /** @description Ошибка валидации */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Файл не найден */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
  getBanners: {
    parameters: {
      query?: {
        filter?: {
          createdAt?: components['schemas']['DateRange'];
        };
        pagination?: components['schemas']['Pagination'];
        sort?: components['schemas']['Sort'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of banners */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            edges: components['schemas']['BannerEdge'][];
            pageInfo: components['schemas']['PageInfo'];
            totalCount: number;
          };
        };
      };
      /** @description Ошибка валидации */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
      /** @description Не найдено */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DomainErrorResponse'];
        };
      };
      /** @description Внутренняя ошибка сервера */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OpenApiValidationError'];
        };
      };
    };
  };
}
