/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/request-otp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Запрос одноразового кода подтверждения
     * @description Создаёт и отправляет OTP пользователю.
     */
    post: operations['requestOtp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify-otp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Подтверждение одноразового кода
     * @description Проверяет OTP и возвращает пару токенов.
     */
    post: operations['verifyOtp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Обновление токенов авторизации
     * @description Обновляет токены по refresh-cookie или заголовку.
     */
    get: operations['refresh'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/complete-profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Дополнение профиля пользователя
     * @description Обновляет профиль после первичного входа.
     */
    post: operations['completeProfile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Выход из аккаунта
     * @description Удаляет текущую сессию пользователя.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение текущего пользователя
     * @description Возвращает профиль текущего пользователя.
     */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Обновление профиля пользователя
     * @description Обновляет профиль текущего пользователя.
     */
    patch: operations['updateProfile'];
    trace?: never;
  };
  '/me/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение списка активных сессий
     * @description Возвращает список активных сессий текущего пользователя.
     */
    get: operations['getMeSessions'];
    put?: never;
    post?: never;
    /**
     * Выход со всех устройств
     * @description Удаляет все сессии текущего пользователя, кроме текущей.
     */
    delete: operations['deleteAllSessions'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/sessions/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Удаление сессии
     * @description Удаляет указанную сессию текущего пользователя.
     */
    delete: operations['deleteSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/avatar/upload-request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Получение presigned URL для загрузки аватара
     * @description Возвращает presigned URL и идентификатор медиа-объекта для аватара пользователя.
     */
    post: operations['avatarUploadRequest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/avatar/preview-upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Получение preview URL для загрузки аватара
     * @description Возвращает preview URL для загрузки аватара.
     */
    post: operations['avatarPreviewUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/upload-request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Получение presigned URL для загрузки файла
     * @description Возвращает presigned URL и идентификатор файла для загрузки.
     */
    post: operations['mediaUploadRequest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/confirm-upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Подтверждение загрузки файлов
     * @description Переводит загруженные файлы из временного хранилища в постоянное.
     */
    post: operations['mediaConfirmUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/preview/{mediaId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение preview URL для временного файла
     * @description Возвращает presigned URL для предпросмотра файла до подтверждения загрузки.
     */
    get: operations['mediaPreview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/banners': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get all banners */
    get: operations['getBanners'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ThrottledErrorResponse: {
      /** @enum {string} */
      code: 'throttled';
      message?: string;
      /** @description Рекомендованная задержка перед повторной попыткой */
      retryAfterSec: number;
    };
    ErrorResponse: {
      /** @description Код ошибки для обработки на клиенте */
      code: string;
      /** @description Человекочитаемое описание ошибки */
      message?: string;
      /** @description Дополнительные детали ошибки */
      details?: {
        [key: string]: unknown;
      };
    };
    TokenPair: {
      /** @description JWT access-токен */
      accessToken: string;
      /** @description JWT refresh-токен */
      refreshToken: string;
    };
    /** @enum {string} */
    MediaVisibility: 'PUBLIC' | 'PRIVATE';
    LinkMediaData: {
      bucket: string;
      objectKey: string;
      /** @description Идентификатор загруженного медиа-объекта */
      mediaId: string;
      visibility: components['schemas']['MediaVisibility'];
      contentType?: string;
    };
    Avatar: {
      /** Format: uri */
      largeUrl: string;
      /** Format: uri */
      mediumUrl: string;
      /** Format: uri */
      smallUrl: string;
      /** Format: uri */
      thumbUrl: string;
    };
    User: {
      /**
       * Format: uuid
       * @description Уникальный идентификатор пользователя
       */
      id: string;
      /** @description Телефон в формате E.164 */
      phoneNumber: string;
      fullName?: string;
      avatar?: components['schemas']['Avatar'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserSession: {
      /**
       * Format: uuid
       * @description Идентификатор сессии
       */
      id: string;
      /**
       * Format: date-time
       * @description Дата создания сессии
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Дата истечения сессии
       */
      expiresAt: string;
    };
    GetMediaUploadUrlInput: {
      contentType?: string;
    };
    GetMediaUploadUrlResult: {
      bucket: string;
      objectKey: string;
      mediaId: string;
      visibility: components['schemas']['MediaVisibility'];
      contentType?: string;
      /** Format: uri */
      url: string;
    };
    UploadRequest: {
      name: string;
      mimeType: string;
      bucket: string;
    };
    UploadRequestResult: {
      fileId: string;
      /** Format: uri */
      uploadUrl: string;
    };
    ConfirmUploadInput: {
      fileIds: string[];
    };
    PreviewDownloadUrlResult: {
      /** Format: uri */
      url: string;
    };
    DateRange: {
      /** Format: date-time */
      from?: string;
      /** Format: date-time */
      to?: string;
    };
    Pagination: {
      after?: string;
      before?: string;
      first?: number;
      last?: number;
    };
    /** @enum {string} */
    SortDirection: 'ASC' | 'DESC';
    Sort: {
      direction?: components['schemas']['SortDirection'];
      field?: string;
    };
    BannerFile: {
      /** Format: uuid */
      id: string;
      /** Format: uri */
      url: string;
    };
    Banner: {
      /** Format: date-time */
      createdAt: string;
      /** Format: uuid */
      id: string;
      isNew: boolean;
      logo: components['schemas']['BannerFile'];
      opacity: number;
      sequence: number;
      subtitle?: string | null;
      title?: string | null;
      url?: string | null;
    };
    BannerEdge: {
      cursor?: string | null;
      node: components['schemas']['Banner'];
    };
    PageInfo: {
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
    Error: {
      statusCode: number;
      message: string;
      error?: string;
    };
  };
  responses: {
    /** @description Resource not found */
    NotFoundError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  requestOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Телефон в формате E.164 */
          phoneNumber: string;
          /**
           * @description Канал доставки OTP
           * @enum {string}
           */
          channel?: 'sms' | 'whatsapp';
          /** @description Локаль для текстов уведомлений */
          locale?: string;
        };
      };
    };
    responses: {
      /** @description OTP отправлен */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Рекомендованная задержка до следующего запроса OTP */
            nextRetrySec?: number;
          };
        };
      };
      /** @description Слишком много запросов */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ThrottledErrorResponse'];
        };
      };
    };
  };
  verifyOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Телефон в формате E.164 */
          phoneNumber: string;
          /** @description Код подтверждения из SMS */
          code: string;
        };
      };
    };
    responses: {
      /** @description Авторизация успешна */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                /** @enum {string} */
                type: 'authenticated';
                /** @description JWT access-токен */
                accessToken: string;
                /** @description JWT refresh-токен */
                refreshToken: string;
              }
            | {
                /** @enum {string} */
                type: 'new_registration';
                /** @description Идентификатор сессии регистрации */
                registrationSessionId: string;
              };
        };
      };
      /** @description Некорректный запрос */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Превышено количество попыток */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            code: 'otp_attempts_exceeded';
            message?: string;
            retryAfterSec?: number;
          };
        };
      };
      /** @description Слишком много запросов */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ThrottledErrorResponse'];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header: {
        'x-refresh-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Токены обновлены */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPair'];
        };
      };
      /** @description Невалидный refresh-токен */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  completeProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Идентификатор сессии регистрации из verifyOtp */
          registrationSessionId: string;
          fullName?: string;
          avatarMedia?: components['schemas']['LinkMediaData'];
        };
      };
    };
    responses: {
      /** @description Профиль создан, токены выданы */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: components['schemas']['User'];
            /** @description JWT access-токен */
            accessToken: string;
            /** @description JWT refresh-токен */
            refreshToken: string;
          };
        };
      };
      /** @description Некорректный запрос */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Сессия удалена */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Профиль пользователя */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Полное имя пользователя */
          fullName: string;
        };
      };
    };
    responses: {
      /** @description Обновлённый профиль */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Невалидное имя */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getMeSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Список сессий */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            sessions: components['schemas']['UserSession'][];
          };
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteAllSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Все сессии удалены */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Сессия удалена */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Сессия не найдена */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  avatarUploadRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GetMediaUploadUrlInput'];
      };
    };
    responses: {
      /** @description Presigned URL для загрузки */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetMediaUploadUrlResult'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  avatarPreviewUpload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LinkMediaData'];
      };
    };
    responses: {
      /** @description URL превью аватара */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Avatar'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  mediaUploadRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UploadRequest'];
      };
    };
    responses: {
      /** @description Presigned URL для загрузки */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadRequestResult'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  mediaConfirmUpload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmUploadInput'];
      };
    };
    responses: {
      /** @description Загрузка подтверждена */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': Record<string, never>;
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Файл не найден */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  mediaPreview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mediaId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Preview URL */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreviewDownloadUrlResult'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Файл не найден */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getBanners: {
    parameters: {
      query?: {
        filter?: {
          createdAt?: components['schemas']['DateRange'];
        };
        pagination?: components['schemas']['Pagination'];
        sort?: components['schemas']['Sort'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of banners */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            edges: components['schemas']['BannerEdge'][];
            pageInfo: components['schemas']['PageInfo'];
            totalCount: number;
          };
        };
      };
      404: components['responses']['NotFoundError'];
    };
  };
}
